### ISSUE TITLE
[Front-End] Design a front-end implementation for a log-in page

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-frontend#10]
We are designing a log-in page for the user to interact with. 
Contemplating on what software to handle this rough sketch of a design. 
If you have any ideas. Let me know! Otherwise, I will continue on research,

**Comment by endepointe** [comment]
Svelte front end with a Rust backend api. new repo added: 

https://github.com/SecurityLogMiner/log-collection-api

**Comment by Jicxer** [comment]
![Image](https://github.com/SecurityLogMiner/log-collection-frontend/assets/79224427/6a7723de-cae0-4bc5-94d7-4fa54ecfde07)

Image has a design for the login page. I may want to tweak it to make it much prettier.

**Comment by Jicxer** [comment]
I plan to link all the sites for a functional front-end per stated in our SDA:
[SDA](https://github.com/SecurityLogMiner/log-collection-documentation/blob/draft-sda/SDA.md)

> Web Front-End Component
> The web frontend will provide the user registration, account login, and distribution interface for the following:

> TLS certificates and their private keys
> ability to copy their OTP (important because message key is not preserved)
> software binary distribution.
> quick glance of existing log sources (not the log data itself)
> The instance IP and port connected to their account
> The web frontend will also house the user documentation. See (documentation)[#documentation-component] section.
