### ISSUE TITLE
[Front-End] Allow user registration

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-frontend#15]
Allow for user to register a specific account for login and authorization.

This is bare-bones as of right now but what would you guys think would be a good sign-up method?
Should they confirm through email?

**Comment by Jicxer** [comment]
I am looking into auth0, and it seems that that API will handle user registration and login. I would assume utilizing an existing program for user log-in || sign-up would be more efficient than re-inventing the wheel. 
I'm in finals, but I've already started looking into this and its implementation. I'll update you guys as I go.

**Comment by endepointe** [comment]
the api, server, and client just need the user email. The api endpiont will receive the user email and trigger the UUID on the server side. 

Auth0 just makes it easy to authenticate a user. It is not the backbone of the service at all.

**Comment by endepointe** [comment]
this has been completed.
