### ISSUE TITLE
[Front-End] User log-in functionality

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-frontend#16]
Allow a user to create an account and be able to log in into the web-app

**Comment by Jicxer** [comment]
Turns out Auth0 deploys a log-in screen for us. Making the log-in and sign up page now seems a little redudant

**Comment by endepointe** [comment]
ok. keeping open while the api is being developed to handle the requests coming from the webapp

**Comment by endepointe** [comment]
redundant issue and completed
