### ISSUE TITLE
[Front-end] User Registration and Credentials

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-frontend#8]
I assume that we'll be using Svelte for the front-end implementation. Currently looking at sources that showcase Svelte implementation. Still unknown what type of authentication we'd want to require for registration and credentials, but at minimum, we should have a designed page for credentials and registration, such as a login or sign-up page. 

- [x] (https://github.com/SecurityLogMiner/log-collection-frontend/issues/10)
- [x] (https://github.com/SecurityLogMiner/log-collection-frontend/issues/12)
- [x] (https://github.com/SecurityLogMiner/log-collection-frontend/issues/14)
- [ ] (https://github.com/SecurityLogMiner/log-collection-frontend/issues/15)
- [ ] (https://github.com/SecurityLogMiner/log-collection-frontend/issues/16)

**Comment by endepointe** [comment]
maybe something like auth0 will work. the documentation is good:

https://auth0.com/blog/authenticating-svelte-apps/

**Comment by endepointe** [comment]
completed
