### ISSUE TITLE
[Front-End] Create a log-in page for user credential/registration

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-frontend#9]
Creating a log-in page interface is important for users to interact with to manage communication with the server after authentication
The purpose of this issue is to focus on design rather than functionality, Authentication, and the logistics soon follow.

- Implement design using Svelte within the front-end repository

**Comment by endepointe** [comment]
closing as this is related to existing task: https://github.com/SecurityLogMiner/log-collection-frontend/issues/10
